### ISSUE TITLE
Missing code on npm

### ISSUE THREAD

**Issue by jedlikowski** [aricodes-oss/parcel-resolver-project-root#1]
Hi,
looks like the version 2.0.1 and 2.0.2 on npm is missing code. Only package.json and Readme.md files are downloaded from npm when installing the package. Also, there is no repo link on npm so it was very hard to find this repository :)

**Comment by aricodes-oss** [comment]
Ah, my apologies on that! I just published version 2.1.1, which removes the build process by translating this to a CJS module and includes a link to the repository on NPM.
